import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { RadioGroup, Dialog, Transition, Switch } from "@headlessui/react";

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-screen min-h-screen flex flex-col justify-center items-center p-4 overflow-y-scroll">
        <Dialog open={true} onClose={() => false} className="relative z-50">
          <div className="fixed inset-0 flex items-center justify-center p-4">
            <Dialog.Panel className="w-full max-w-sm rounded bg-white">
              <Dialog.Title>Complete your order</Dialog.Title>
              <div className="mt-2">
                <p className="text-sm text-gray-500">asdada</p>
              </div>
            </Dialog.Panel>
          </div>
        </Dialog>
      </div>
    </>
  );
};

export default Home;
